# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ZPZThirdFrameworkPractice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking'
  # Pods for ZPZThirdFrameworkPractice

  target 'ZPZThirdFrameworkPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZPZThirdFrameworkPracticeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
