# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'ZPZMJRefreshExplore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZPZMJRefreshExplore
  pod 'MJRefresh'
  target 'ZPZMJRefreshExploreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZPZMJRefreshExploreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
